# Generated by Django 4.2.4 on 2023-09-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstaff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalstaff',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='job',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='shift',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='title',
            field=models.CharField(default='Other', max_length=255),
        ),
    ]
